### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by zwergius** [josephfrazier/prettier_d#73]
macOS 11.2.1
node v15.8.0

running:  `npm install -g https://github.com/josephfrazier/prettier_d`

produces the following:

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/2060308/108231745-5c954a00-7142-11eb-932d-71aa757c9bd8.png">

**Comment by josephfrazier** [comment]
Thanks for the report, @zwergius, I was able to reproduce the issue locally. It looks like I might need to change some dependency versions so that peer dependency versions don't conflict with each other.

**Comment by josephfrazier** [comment]
ok, I just merged a fix. Let me know if you're continuing to see errors!

**Comment by zwergius** [comment]
Hi @josephfrazier,

Appreciate your quick fix 🙏

So first part seems to be fixed, but still getting this error:

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/2060308/108332063-ad9f4f80-71cf-11eb-92e8-1cf70cd217f4.png">

**Comment by josephfrazier** [comment]
Hmm, I see... and am able to reproduce it locally. I'll have to do some digging around to fix it (maybe it's just a matter of upgrading more dependencies?), but in the mean time, you might be able to install it using [Yarn](https://yarnpkg.com/):

```
yarn global add https://github.com/josephfrazier/prettier_d
```

**Comment by josephfrazier** [comment]
ok, I tried upgrading the dependency that's pulling in @babel/parser, but that hasn't worked for me: https://github.com/josephfrazier/prettier_d/pull/76

will keep looking

**Comment by josephfrazier** [comment]
hi @zwergius, I don't currently have the time to maintain `prettier_d`, but I'd recommend looking into `prettier_d_slim`, as it seems to have worked better for others. See here for details: https://github.com/josephfrazier/prettier_d/issues/83#issuecomment-815238415

**Comment by zwergius** [comment]
Thanks @josephfrazier I'll try that out instead!
